a = int(input('Primeiro valor: '))
b = int(input('Segundo valor: '))
c = int(input('Terceiro valor: '))
menor = min(a, b, c)
maior = max(a, b, c)
print('O menor valor digitado foi {}'.format(menor))
print('O maior valor digitado foi {}'.format(maior))