a = input("Digite algo:")
print("Isso é uma", type(a))
print("É somente espaços?", a.isspace())
print("É um número?", a.isnumeric())
print("É alfabétio?", a.isalpha())
print("É alphanúmerico?". a.isalnum())
print("Está tudo em maisuculo?", a.isupper())
print("Está em minusculo?", a.islower())
print("Esta capitalizado?", a.istitle())
